### ISSUE TITLE
Constant time algorithm?

### ISSUE THREAD

**Issue by dcousens** [sindresorhus/buffer-equals#1]
Thoughts on adding `constant.js` to resolve to `buffer-equals/constant`?

**Comment by sindresorhus** [comment]
What would be the difference in this case? What do you need it for?

**Comment by dcousens** [comment]
A constant time comparison inside an application.
I currently use the library, and would prefer the above syntax if possible.

The difference would be:

``` javascript
var result = 0
for (var i = 0; i < length; ++i) {
  result |= a[i] ^ b[i]
}

return result === 0
```

**Comment by sindresorhus** [comment]
I'm still not sure why you need something like that? In what scenario would you want it to be possibly slower just to have it be constant time?

**Comment by dcousens** [comment]
@sindresorhus https://en.wikipedia.org/wiki/Timing_attack

**Comment by sindresorhus** [comment]
Ah, makes sense. I didn't think of that use-case. I decided to not add it to this module as I want it to remain a strict polyfill of the core method. Instead I made a separate module: https://github.com/sindresorhus/buffer-equals-constant Is this what you had in mind?

**Comment by dcousens** [comment]
Close enough :+1: ,  I was tempted to make that module and put it under https://github.com/crypto-browserify,  but figured I'd ask about this first.

Ha
